# Generated by Django 5.1 on 2024-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('full_name', models.CharField(max_length=100)),
                ('pin_no', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('gmail', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
